SELECT 'Suganth' as Name from Dual;

SELECT JOB, SAL, COUNT(*)
FROM COPY_EMP
WHERE JOB = 'MANAGER'
GROUP BY JOB, SAL
HAVING SAL > 2500
ORDER BY SAL ASC;

SELECT *FROM COPY_EMP;

--Execution order
/*
FROM
WHERE
GROUP BY
HAVING
SELECT
ORDER BY
LIMIT/OFEST
*/

--Self Join - to map the manager

SELECT
EMP.EMPNO AS EMPLOYE_NO,
EMP.ENAME AS EMPLOYE_NAME,
MNG.EMPNO AS MGR_EMP_NO,
MNG.ENAME AS MGR_NAME
FROM COPY_EMP EMP
JOIN COPY_EMP MNG
ON EMP.MGR = MNG.EMPNO;
--WHERE MNG.EMPNO = 7839;

SELECT * FROM COPY_EMP WHERE MGR = 7839;

--Sub Query

SELECT * FROM COPY_DEPT; 
SELECT * FROM COPY_EMP;

SELECT * 
FROM COPY_EMP
WHERE DEPTNO IN (
    SELECT DEPTNO 
    FROM COPY_DEPT 
    WHERE DNAME IN ('ACCOUNTING', 'SALES')
    );

-- CTE - Common table expression

WITH ACC_ASSOCIATES 
AS
(
    SELECT 
    EMP.EMPNO,
    EMP.ENAME,
    EMP.JOB,
    DEPT.DNAME,
    CASE
        WHEN EMP.JOB = 'PRESIDENT' THEN 'S2'
        WHEN EMP.JOB = 'MANAGER' THEN 'S1'
        ELSE 'J'
    END AS GRADE
    FROM COPY_EMP EMP
    JOIN COPY_DEPT DEPT 
    ON EMP.DEPTNO = DEPT.DEPTNO
    WHERE DEPT.DNAME = 'ACCOUNTING'
),
--SELECT * FROM ACC_ASSOCIATES;
SALES_ASSOCIATES 
AS
(
   SELECT 
    EMP.EMPNO,
    EMP.ENAME,
    EMP.JOB,
    DEPT.DNAME,
    CASE
        WHEN EMP.JOB = 'PRESIDENT' THEN 'S2'
        WHEN EMP.JOB = 'MANAGER' THEN 'S1'
        ELSE 'J'
    END AS GRADE
    FROM COPY_EMP EMP
    JOIN COPY_DEPT DEPT 
    ON EMP.DEPTNO = DEPT.DEPTNO
    WHERE DEPT.DNAME = 'SALES' 
),
--SELECT * FROM SALES_ASSOCIATES;
UNI
AS
(
    SELECT * FROM ACC_ASSOCIATES
    UNION
    SELECT * FROM SALES_ASSOCIATES
)
SELECT * FROM UNI;

--WINDOW Function
/*
A window function in SQL performs a calculation across a 
set of related rows without collapsing those rows into one row.
*/

SELECT * FROM COPY_EMP;
-- Give average salary in department, show in the all rows of COPY_EMP
SELECT 
EMPNO,
ENAME,
JOB,
MGR,
DEPTNO,
AVG(SAL)OVER (
    PARTITION BY DEPTNO
) AS AVG_SAL
FROM COPY_EMP;

-- Total salary spent on the department
SELECT 
EMPNO,
ENAME,
JOB,
MGR,
DEPTNO,
SUM(SAL)OVER (
    PARTITION BY DEPTNO
) AS AVG_SAL
FROM COPY_EMP;

--ROW_NUM - Give unique number to each row
SELECT
EMPNO,
ENAME,
DEPTNO, 
JOB, 
SAL,
ROW_NUMBER() OVER(ORDER BY EMPNO DESC) AS ROW_NUM
FROM COPY_EMP;

SELECT
EMPNO,
ENAME,
DEPTNO, 
JOB, 
SAL,
ROW_NUMBER() OVER(PARTITION BY DEPTNO ORDER BY EMPNO DESC) AS ROW_NUM
FROM COPY_EMP;

--RANK
SELECT 
ENAME,
DEPTNO, 
OB, 
SAL,
RANK() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) AS SAL_RANK
FROM COPY_EMP;

SELECT 
ENAME,
DEPTNO, 
JOB, 
SAL,
RANK() OVER (ORDER BY SAL DESC) AS SAL_RANK
FROM COPY_EMP;

--DENSE_RANK - Same sal get same RANK without GAP

SELECT
EMPNO, 
ENAME,
DEPTNO, 
JOB, 
SAL,
DENSE_RANK() OVER (ORDER BY SAL DESC) AS SAL_RANK
FROM COPY_EMP;

--LNG

SELECT
EMPNO, 
ENAME,
DEPTNO, 
JOB, 
SAL,
LAG(SAL) OVER (ORDER BY SAL DESC) AS PREV_SAL
FROM COPY_EMP;

--LEAD
SELECT
EMPNO, 
ENAME,
DEPTNO, 
JOB, 
SAL,
LEAD(SAL) OVER (ORDER BY SAL DESC) AS NEXT_SAL
FROM COPY_EMP;

--Problems
--Find second-highest salary

SELECT * FROM
(
    SELECT
    EMPNO, 
    ENAME,
    DEPTNO, 
    JOB, 
    SAL,
    DENSE_RANK() OVER(ORDER BY SAL DESC) SAL_RANK
    FROM COPY_EMP
)WHERE SAL_RANK = 2;

--Find duplicate records

-- INSERT DUPLICATE INTO COPY_EMP
INSERT INTO COPY_EMP
SELECT * FROM COPY_EMP
WHERE EMPNO IN (7839, 7698);

SELECT * FROM(
    SELECT
    EMPNO, 
    ENAME,
    DEPTNO, 
    JOB, 
    SAL,
    DENSE_RANK() OVER(PARTITION BY EMPNO ORDER BY ROWID) EMP_RANK
    FROM COPY_EMP
)WHERE EMP_RANK >1;

--Delete Duplicate

DELETE FROM COPY_EMP
WHERE ROWID IN
(
    SELECT ROWID--, EMPNO, ENAME
    FROM
    (
        SELECT
        EMPNO, 
        ENAME,
        DEPTNO, 
        JOB, 
        SAL,
        DENSE_RANK() OVER(PARTITION BY EMPNO ORDER BY ROWID) EMP_RANK
        FROM COPY_EMP
    )WHERE EMP_RANK >1
    );

--Find employees earning more than department average
SELECT * FROM(
    SELECT
    EMPNO, 
    ENAME,
    DEPTNO, 
    JOB, 
    SAL,
    AVG(SAL) OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AVG_DEPT_SAL
    FROM COPY_EMP
)WHERE SAL >= AVG_DEPT_SAL;

--Runnin total
-- Not the correct example
SELECT * FROM(
    SELECT
    EMPNO, 
    ENAME,
    DEPTNO, 
    JOB, 
    SAL,
    SUM(SAL) OVER(ORDER BY SAL) RUNNING_TOTAL
    FROM COPY_EMP
);





