SELECT * FROM SCOTT.DEPT;

SELECT * FROM SCOTT.EMP;

--MAX SALARY
SELECT * FROM SCOTT.EMP
WHERE SAL = (SELECT MAX(SAL) FROM SCOTT.EMP);

SELECT * FROM SCOTT.EMP
ORDER BY SAL DESC
FETCH FIRST 1 ROW ONLY;


SELECT 1 FROM SCOTT.EMP
WHERE EMPNO = 7839;

SELECT * FROM SCOTT.EMP
WHERE SAL > ALL(SELECT SAL FROM SCOTT.EMP WHERE JOB = 'MANAGER');

SELECT * FROM SCOTT.EMP
WHERE SAL > ANY(SELECT SAL FROM SCOTT.EMP WHERE JOB = 'MANAGER');

--View
CREATE VIEW  V_MANAGER AS
SELECT * FROM COPY_EMP
WHERE JOB = 'MANAGER';

SELECT * FROM 
COPY_EMP E1 JOIN COPY_EMP E2
ON E1.MGR = E2.EMPNO;

SELECT E1.EMPNO AS Employee_ID,
       E1.ENAME AS Employee_Name,
       E2.ENAME AS Manager_Name
FROM COPY_EMP E1
JOIN COPY_EMP E2
ON E1.MGR = E2.EMPNO;

--Create index

CREATE index IDX_EMP_SAL 
ON EMP(SAL);

-- CREATE plain able from exixing able
CREATE TABLE TEST_BL
AS
SELECT * FROM 
SCOTT.EMP WHERE 1 = 0;

SELECT * FROM TEST_BL;


--CREATE PROCEDURE
CREATE OR REPLACE PROCEDURE SAY_HELLO(
    person_name IN VARCHAR
)
IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Hello from Oracle!' || person_name);
END;
/

EXECUTE SAY_HELLO('Suganth');

CREATE OR REPLACE PROCEDURE ADD_NUM(
    NUM1 IN NUMBER,
    NUM2 IN NUMBER,
    TOTAL OUT NUMBER
)
IS
BEGIN
    TOTAL := NUM1+NUM2;
END;
/

DECLARE
    RES NUMBER;
    NUM1 NUMBER;
    NUM2 NUMBER;
BEGIN
    NUM1 := 1;
    NUM2 := 2;

    ADD_NUM(NUM1, NUM2, RES);

    DBMS_OUTPUT.PUT_LINE('TOTAL OF ' || NUM1 || ' + ' || NUM2 || ' = ' || RES);
END;
/

--FUNCTIONS
CREATE OR REPLACE FUNCTION ADD_NUM_FUN(
    NUM1 NUMBER,
    NUM2 NUMBER
)
RETURN NUMBER
IS
BEGIN
    RETURN NUM1+NUM2;
EXCEPTION
    WHEN ZERO_DIVIDE THEN
        RETURN NULL;
END;
/

--EXECUTE FUNCTION
SELECT ADD_NUM_FUN(1,2) FROM DUAL;

--EXAMPLE
SELECT MAX(SAL) FROM COPY_EMP;

DECLARE
    MAX_SAL NUMBER;
    COM_P NUMBER := 13;
    PAY NUMBER;
BEGIN
    SELECT MAX(SAL) INTO MAX_SAL FROM COPY_EMP;
    PAY := MAX_SAL + (MAX_SAL*(13/100));
    DBMS_OUTPUT.PUT_LINE('MAX SALARY IS WITH COMMISION ' || PAY);
END;
/

--RANK()
SELECT * FROM COPY_EMP;

SELECT ENAME,DEPTNO, JOB, SAL,
RANK() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) AS SAL_RANK
FROM COPY_EMP;

SELECT DEPTNO, JOB, SAL,
RANK() OVER (ORDER BY SAL DESC) SAL_RANK
FROM COPY_EMP;

